channels:
  - conda-forge
  - defaults
  - conda-forge/label/broken
dependencies:
  - ipython
  - pip
  - matplotlib
  - numpy
  - scipy
  - pandas
  - requests 
  - scikit-learn
  - seaborn
  - jupyter_contrib_nbextensions
  - ipywidgets
  - requests
  - pip:
    - eurostatapiclient
    - jsonstat.py
    - pandaSDMX
    - dbnomics
    - geojson
    - folium
    - geopandas
    - eurostat
    - plotly
    - descartes
    - rtree
    - google.colab
    - datetime
  
