channels:
  - conda-forge
  - defaults
#  - conda-forge/label/broken
dependencies:
  - ipython
  - pip
  - matplotlib
  - numpy
  - scipy
  - pandas
  - requests 
  - scikit-learn
  - seaborn
  - jupyter_contrib_nbextensions
  - ipywidgets
  - google-colab
  - folium
  - geopandas
  - selenium
  - papermill
  - xgboost
  - plotly
  - tensorflow
  - keras
  - httplib2
  - bs4
  - pip:
    - eurostatapiclient
    - openpyxl
    - optuna
    - geopy
